set(LV_EDITOR_PROJECT_SOURCES)
list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/arc/arc_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/bar/bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/button/button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/slider/slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/text_box/text_box_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/text_input/text_input_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/toggle/toggle_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/layout/base_box/base_box_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/layout/container/container_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/layout/panel/panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/layout/window/window_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/list/list_item_switch/list_item_switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/list/list_item/list_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/list/list_section/list_section_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/list/list_separator/list_separator_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/list/list/list_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/overlays/popup/popup_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/typography/h1/h1_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/typography/h2/h2_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/typography/h3/h3_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/typography/h4/h4_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/typography/h5/h5_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/typography/text/text_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_body_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h1_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h2_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h3_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h4_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h5_data.c
  ${CMAKE_CURRENT_LIST_DIR}/lvgl_open_template_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/lvgl_open_template.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_components_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_home_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_gen.c)